// generated by stringer -type Color; DO NOT EDIT

package engine

import "fmt"

const _Color_name = "NoColorBlackWhite"

var _Color_index = [...]uint8{0, 7, 12, 17}

func (i Color) String() string {
	if i >= Color(len(_Color_index)-1) {
		return fmt.Sprintf("Color(%d)", i)
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
