// Copyright 2014-2017 The Zurichess Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file was generated by bitbucket.org/zurichess/tuner/extract

// +build !coach

package engine

const (
	fNoFigure           int = 0
	fPawn               int = 1
	fKnight             int = 2
	fBishop             int = 3
	fRook               int = 4
	fQueen              int = 5
	fKing               int = 6
	fPawnMobility       int = 7
	fMinorsPawnsAttack  int = 8
	fMajorsPawnsAttack  int = 9
	fKnightFile         int = 10
	fKnightRank         int = 18
	fKnightAttack       int = 26
	fBishopFile         int = 27
	fBishopRank         int = 35
	fBishopAttack       int = 43
	fRookFile           int = 44
	fRookRank           int = 52
	fRookAttack         int = 60
	fRookOnOpenFile     int = 61
	fRookOnSemiOpenFile int = 62
	fQueenFile          int = 63
	fQueenRank          int = 71
	fQueenAttack        int = 79
	fPawnSquare         int = 80
	fBackwardPawns      int = 144
	fConnectedPawns     int = 145
	fDoubledPawns       int = 146
	fIsolatedPawns      int = 147
	fKingFile           int = 148
	fKingRank           int = 156
	fKingAttack         int = 164
	fKingShelter        int = 165
	fPassedPawnRank     int = 166
)
