// Copyright 2014-2017 The Zurichess Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file was generated by bitbucket.org/zurichess/tuner/extract

// +build !coach

package engine

const (
	fNoFigure       int = 0
	fPawn           int = 1
	fKnight         int = 2
	fBishop         int = 3
	fRook           int = 4
	fQueen          int = 5
	fKing           int = 6
	fBishopFile     int = 7
	fBishopRank     int = 15
	fBishopAttack   int = 23
	fQueenFile      int = 24
	fQueenRank      int = 32
	fQueenAttack    int = 40
	fKingFile       int = 41
	fKingRank       int = 49
	fRookFile       int = 57
	fRookRank       int = 65
	fRookAttack     int = 73
	fPawnSquare     int = 74
	fBackwardPawns  int = 138
	fConnectedPawns int = 139
	fDoubledPawns   int = 140
	fIsolatedPawns  int = 141
	fPassedPawnRank int = 142
	fKnightFile     int = 150
	fKnightRank     int = 158
	fKnightAttack   int = 166
)
