// Copyright 2014-2017 The Zurichess Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file was generated by bitbucket.org/zurichess/tuner/extract

// +build !coach

package engine

const (
	fNoFigure     int = 0
	fPawn         int = 1
	fKnight       int = 2
	fBishop       int = 3
	fRook         int = 4
	fQueen        int = 5
	fKing         int = 6
	fBishopAttack int = 7
	fRookAttack   int = 8
	fQueenAttack  int = 9
	fKnightAttack int = 10
)
