// generated by stringer -type hashKind; DO NOT EDIT

package engine

import "fmt"

const _hashKind_name = "noEntryexactfailedLowfailedHigh"

var _hashKind_index = [...]uint8{0, 7, 12, 21, 31}

func (i hashKind) String() string {
	if i >= hashKind(len(_hashKind_index)-1) {
		return fmt.Sprintf("hashKind(%d)", i)
	}
	return _hashKind_name[_hashKind_index[i]:_hashKind_index[i+1]]
}
