// Copyright 2014-2017 The Zurichess Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file was generated by bitbucket.org/zurichess/tuner.

// +build !coach

package engine

// Weights stores the network parameters.
// Network has train error 0.07091402 and validation error 0.07095083.
var Weights = [...]Score{
	{M: -100, E: 146}, {M: 10890, E: 18652}, {M: 44782, E: 43383}, {M: 46326, E: 46965}, {M: 52824, E: 83227}, {M: 105237, E: 148542}, {M: 59, E: 24},
}
