// Copyright 2014-2017 The Zurichess Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file was generated by bitbucket.org/zurichess/tuner.

// +build !coach

package engine

// Weights stores the network parameters.
// Network has train error 0.06735051 and validation error 0.06742997.
var Weights = [...]Score{
	{M: 109, E: 55}, {M: 13373, E: 19423}, {M: 42587, E: 31728}, {M: 44346, E: 40779}, {M: 54047, E: 80455}, {M: 112179, E: 134579}, {M: 148, E: 39}, {M: 1354, E: 1211},
	{M: 1210, E: 761}, {M: 63, E: 2189}, {M: 1281, E: 2314},
}
