// generated by stringer -type Figure; DO NOT EDIT

package engine

import "fmt"

const _Figure_name = "PawnKnightBishopRookQueenKing"

var _Figure_index = [...]uint8{4, 10, 16, 20, 25, 29}

func (i Figure) String() string {
	i -= 1
	if i >= Figure(len(_Figure_index)) {
		return fmt.Sprintf("Figure(%d)", i+1)
	}
	hi := _Figure_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _Figure_index[i-1]
	}
	return _Figure_name[lo:hi]
}
