// generated by stringer -type HashKind; DO NOT EDIT

package engine

import "fmt"

const _HashKind_name = "NoKindExactFailedLowFailedHigh"

var _HashKind_index = [...]uint8{6, 11, 20, 30}

func (i HashKind) String() string {
	if i >= HashKind(len(_HashKind_index)) {
		return fmt.Sprintf("HashKind(%d)", i)
	}
	hi := _HashKind_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _HashKind_index[i-1]
	}
	return _HashKind_name[lo:hi]
}
